version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./socialfeedwebapp_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/socialfeedwebapp
    depends_on:
      - mongo

  frontend:
    build: ./socialfeedwebappfront
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: 