version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    image: snehanagpure/kia_socialfeedwebapp-backend:latest
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/socialfeedwebapp
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./socialfeedwebapp_backend/uploads:/app/uploads
  frontend:
    image: snehanagpure/kia_socialfeedwebapp-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  mongo-data: 